[DEFAULT]

# Manage a "pristine-tar" branch:
pristine-tar = True
pristine-tar-commit = True

# Use Debian-style branch names:
upstream-branch=upstream/latest
ubuntu-branch=ubuntu/latest

#[import-orig]
#postimport = dch -v%(version)s New upstream release; git add debian/changelog; debcommit
#upstream-vcs-tag = %(version%~%.)s

[buildpackage]
git-cleaner = git clean -fdx
git-ignore-new = True
git-builder = sbuild
git-debsign-key = A98D2EFD62CC29CC74AD8A596178B3A39D745AAC
